### ISSUE TITLE
Unable to enable ssl on cloud-mysql instance

### ISSUE THREAD

**Issue by balloray** [cloudfoundry/csb-brokerpak-gcp#152]
**Is your feature request related to a problem? Please describe.**
Hello ,
I have this service broker installed on our environment but it doesn't have ssl enabled when the cloud-sql instances are created.
Please let us know if there is any option to be specified to enable ssl when provisioning the cloudsql-mysql instances?

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by blgm** [comment]
Hi @balloray, there isn't a way to enable TLS on a MySQL instance at the moment. It looks like the functionality was added in the past, and then removed because it was problematic. The write-up suggest that it was something to do with creating a second binding on PostgreSQL, but there isn't much detail or explanation of how that's related. Because it seems that it was problematic in the past, I'm hesitant to simply reinstate it without also improving the testing in that area.
https://github.com/cloudfoundry-incubator/csb-brokerpak-gcp/commit/3a4070fd1164e7edbdfa6db8e2f6696bc9ff8209#

You would be welcome to submit a PR to resolve this. Otherwise it is on our roadmap, but I'm not in a position to predict a timescale.

**Comment by jhvhs** [comment]
TLS on MySQL is now always on. Google [generates a CA](https://cloud.google.com/sql/docs/mysql/configure-ssl-instance) for each service instance, so the CA, the client certificate and client key are returned as part of the binding credentials. When using java applications, the CA certificate has to be imported into the default java trust store via a custom script. Additionally the hostname specified in the issued server certificate will never match the hostname in the connection string, so the hostname verification has to be disabled for the TLS connection to work. For example, the `CN` field is set to `<GCP project name>:<DB Instance Name>`, while the `SAN` field is in the format of `<some opaque GUID>.<AZ name>.sql.goog`.
